'use client';

import { useState } from 'react';
import { FileBarChart2, Download, Mail, FileSpreadsheet, Zap, CheckCircle2 } from 'lucide-react';
import Badge from '@/components/ui/Badge';

const reportTemplates = [
  {
    id: 'monthly_production',
    name: 'Monthly Production Report',
    description: 'Complete mine-wise production summary with target vs actual analysis, efficiency metrics, and trend charts',
    icon: '📊',
    category: 'Operations',
    lastGenerated: '2025-07-01',
    pages: 24,
  },
  {
    id: 'safety_audit',
    name: 'Safety Audit Report',
    description: 'Incident log, PPE compliance, training status, violation summary, and DGMS compliance metrics',
    icon: '🛡️',
    category: 'Safety',
    lastGenerated: '2025-07-05',
    pages: 18,
  },
  {
    id: 'maintenance_summary',
    name: 'Equipment Maintenance Summary',
    description: 'Equipment health scores, maintenance performed, breakdown analysis, and AI failure predictions',
    icon: '⚙️',
    category: 'Maintenance',
    lastGenerated: '2025-07-07',
    pages: 32,
  },
  {
    id: 'hr_summary',
    name: 'HR Monthly Summary',
    description: 'Attendance analysis, leave statistics, training completions, and performance appraisal status',
    icon: '👥',
    category: 'HR',
    lastGenerated: '2025-07-01',
    pages: 16,
  },
  {
    id: 'executive_dashboard',
    name: 'Executive Dashboard Report',
    description: 'High-level KPIs for Director/CMD — production, equipment health, safety score, financial overview',
    icon: '📋',
    category: 'Executive',
    lastGenerated: '2025-07-09',
    pages: 8,
  },
  {
    id: 'env_compliance',
    name: 'Environmental Compliance Report',
    description: 'Air quality readings, water discharge, noise levels, dust suppression compliance per MOEF norms',
    icon: '🌿',
    category: 'Environment',
    lastGenerated: '2025-06-30',
    pages: 20,
  },
];

const SAMPLE_REPORT = `# Monthly Production Report — July 2025
## Central Coalfields Limited

---

### Executive Summary

Total production for July 2025 (Month-to-Date) stands at **1,700,500 MT** against a target of **1,940,000 MT**, representing an efficiency of **87.7%**.

---

### Mine-wise Performance

| Mine | Actual (MT) | Target (MT) | Efficiency |
|------|-------------|-------------|-----------|
| Rajrappa | 412,500 | 480,000 | 85.9% |
| Argada | 225,000 | 280,000 | 80.4% |
| Piparwar | 520,000 | 510,000 | **102.0%** ✅ |
| Kuju | 140,000 | 190,000 | ⚠️ 73.7% |
| Dhori | 118,000 | 120,000 | 98.3% |
| Kedla | 285,000 | 360,000 | 79.2% |

### Key Observations

1. **Piparwar mine** is the standout performer at 102% — consider capacity review for Q3.
2. **Kuju mine** is significantly underperforming due to DR-2 drill rig downtime (200+ idle hours). Immediate maintenance authorization recommended.
3. **Argada mine** — Conveyor C-7 breakdown has caused 72 hours of production loss. Motor replacement ETA: 5 days.

### AI Recommendations

> **Action Required:** Authorize ₹38 lakhs for Kuju DR-2 maintenance to prevent Q3 shortfall exceeding 25%. 
> Every additional month of delay costs an estimated ₹2.1 crores in lost production.

---

### Equipment Health Summary

- Average fleet health: **67.4%** (Critical threshold: <70%)
- 2 machines in critical condition requiring immediate attention
- Predicted breakdowns in next 30 days: 3

### Safety Highlights

- Safety incidents this month: **5** (↓ 37.5% vs last month)
- PPE violations: **12** (↓ 57% over 6 months — training program is working)
- Compliance score: **87.3%**

---

*Generated by IntelliMine Copilot AI · ${new Date().toLocaleString('en-IN')}*
*Central Coalfields Limited — Confidential*`;

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState('');
  const [done, setDone] = useState(false);

  const handleGenerate = async (id: string) => {
    setSelectedReport(id);
    setGenerating(true);
    setGeneratedReport('');
    setDone(false);
    // Simulate AI generation
    await new Promise(r => setTimeout(r, 2500));
    setGeneratedReport(SAMPLE_REPORT);
    setGenerating(false);
    setDone(true);
  };

  return (
    <div className="space-y-6 fade-in">
      <div>
        <h1 className="text-2xl font-bold" style={{ color: 'var(--color-text-primary)' }}>Smart Report Generator</h1>
        <p className="text-sm mt-0.5" style={{ color: 'var(--color-text-secondary)' }}>
          AI-assembled reports with charts, analysis, and recommendations
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Report Templates */}
        <div className="space-y-3">
          <h2 className="text-sm font-semibold uppercase tracking-wider" style={{ color: 'var(--color-text-muted)' }}>Report Templates</h2>
          {reportTemplates.map(r => (
            <div key={r.id}
              className="glass-card p-4 cursor-pointer transition-all hover:scale-[1.01]"
              style={selectedReport === r.id ? { borderColor: 'var(--color-blue)', boxShadow: '0 0 20px rgba(59,130,246,0.15)' } : {}}>
              <div className="flex items-start gap-3">
                <span className="text-2xl flex-shrink-0">{r.icon}</span>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <p className="font-semibold text-sm" style={{ color: 'var(--color-text-primary)' }}>{r.name}</p>
                    <Badge variant="muted" size="sm">{r.category}</Badge>
                  </div>
                  <p className="text-xs mb-2 leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>{r.description}</p>
                  <div className="flex items-center justify-between">
                    <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                      Last: {r.lastGenerated} · ~{r.pages} pages
                    </p>
                    <button
                      onClick={() => handleGenerate(r.id)}
                      disabled={generating}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all hover:scale-105 disabled:opacity-50"
                      style={{ background: 'linear-gradient(135deg, #1e40af, #7c3aed)', color: '#fff' }}>
                      <Zap size={11} />
                      {generating && selectedReport === r.id ? 'Generating...' : 'Generate'}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Generated Report Preview */}
        <div className="glass-card overflow-hidden" style={{ maxHeight: '700px' }}>
          {!generatedReport && !generating && (
            <div className="flex flex-col items-center justify-center h-full p-8 text-center">
              <FileBarChart2 size={48} className="mb-4 opacity-20" style={{ color: 'var(--color-blue)' }} />
              <p className="font-semibold" style={{ color: 'var(--color-text-secondary)' }}>Select a report template</p>
              <p className="text-sm mt-1" style={{ color: 'var(--color-text-muted)' }}>AI will generate a complete report with charts, analysis, and recommendations</p>
            </div>
          )}

          {generating && (
            <div className="flex flex-col items-center justify-center h-full p-8 text-center gap-4">
              <div className="w-12 h-12 rounded-2xl flex items-center justify-center animate-pulse"
                style={{ background: 'linear-gradient(135deg, #1e40af, #7c3aed)' }}>
                <Zap size={24} style={{ color: '#fff' }} />
              </div>
              <div>
                <p className="font-semibold" style={{ color: 'var(--color-text-primary)' }}>AI is generating your report...</p>
                <p className="text-sm mt-1" style={{ color: 'var(--color-text-secondary)' }}>Analyzing data, creating charts, writing insights</p>
              </div>
              <div className="flex gap-2 items-center text-sm" style={{ color: 'var(--color-text-muted)' }}>
                {['Fetching data', 'Running analysis', 'Generating narrative', 'Assembling report'].map((step, i) => (
                  <div key={step} className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full bg-blue-400 pulse-green" style={{ animationDelay: `${i * 0.5}s` }} />
                    <span className="text-xs">{step}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {generatedReport && (
            <div className="flex flex-col h-full">
              {/* Export Actions */}
              <div className="flex items-center justify-between px-5 py-3 border-b shrink-0"
                style={{ borderColor: 'var(--color-border)' }}>
                <div className="flex items-center gap-2">
                  <CheckCircle2 size={16} style={{ color: 'var(--color-green)' }} />
                  <span className="text-sm font-semibold" style={{ color: 'var(--color-green)' }}>Report generated</span>
                </div>
                <div className="flex gap-2">
                  {[
                    { icon: <Download size={12} />, label: 'PDF' },
                    { icon: <FileSpreadsheet size={12} />, label: 'Excel' },
                    { icon: <Mail size={12} />, label: 'Email' },
                  ].map(btn => (
                    <button key={btn.label}
                      className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-semibold transition-all hover:scale-105"
                      style={{ background: 'rgba(59,130,246,0.1)', border: '1px solid rgba(59,130,246,0.2)', color: 'var(--color-blue-bright)' }}>
                      {btn.icon} {btn.label}
                    </button>
                  ))}
                </div>
              </div>
              {/* Report content */}
              <div className="flex-1 overflow-y-auto p-5 text-sm" style={{ color: 'var(--color-text-secondary)', lineHeight: 1.8 }}>
                <pre className="whitespace-pre-wrap font-sans" style={{ color: 'var(--color-text-primary)', fontSize: 13 }}>{generatedReport}</pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
